;;;; cl-tesseract.lisp

(in-package #:cl-tesseract)

;;; "cl-tesseract" goes here. Hacks and glory await!

(defun tesseract-version ()
  "Returns Tesseract version as string."
  (tess-version))

#| On SBCL, libtesseract 3.04.00 signalled a SIGFPE while carrying out text recognition,
under the old Cube OCR engine's numerics. While this had no effect using CCL, it required a
SBCL-specific macro on that implementation invoking SB-INT:WITH-FLOAT-TRAPS-MASKED. Under
Tesseract 5.5's LSTM-only engine this was not observed to reproduce in testing (2026-07-26),
but the mask is left in place regardless -- it is a no-op if genuinely unneeded, and cheap
insurance against a rarer input triggering it than was tried. |#

(defmacro mask-sigfpe (&body body)
  "Under SBCL, this macro wraps body with SB-INT:WITH-FLOAT-TRAPS-MASKED to prevent a SIGFPE
generated by libtesseract from causing a non-recoverable error. On other implementations,
simply wraps body in a PROGN."
  #+sbcl
  `(sb-int:with-float-traps-masked (:invalid :divide-by-zero)
    ,@body)
  #-sbcl
  `(progn ,@body))

(defmacro with-base-api (api-name &body body &aux (handle (gensym)))
  "This macro creates a TessBaseAPI using TessBaseAPICreate and binds it to api-name. It
wraps body with an UNWIND-PROTECT form to ensure that TessBaseAPIEnd and TessBaseAPIDelete
are called on api-name upon exit."
  `(let (,handle)
     (unwind-protect
         (let ((,api-name (setq ,handle (tess-base-api-create))))
           ,@body)
       (tess-base-api-end ,handle)
       (tess-base-api-delete ,handle))))

(defun init-tess-api (api lang)
  "Calls TessBaseAPIInit3 on api and sets lang, which should be a string naming a
.traineddata file in *tessdata-directory*. Attempting to set a language that is not available
will raise an error."
  (let ((return-code (tess-base-api-init3 api *tessdata-directory* lang)))
    (case return-code
      (-1 (error "Failure to initialize TessBaseAPI."))
      (0 t))))

(defun process-pages (api truename)
  "This function calls TessBaseAPIProcessPages on api, which should be an initialized
TessBaseAPI, and then uses Leptonica to load the image found at truename (which must be a
string containing the complete path to the file). It then runs OCR on the image. On SBCL,
the division-by-zero float trap is masked to prevent it from causing a non-recoverable error.

The details of your Leptonica installation will determine exactly what image formats this
function can process successfully.

Returns T on success, otherwise signals error."
  (mask-sigfpe
   (let ((return-code (tess-base-api-process-pages api truename "" 0 (null-pointer))))
    (case return-code
      (1 t)
      (t (error "TessBaseAPIProcessPages returned failure."))))))

(defun owned-foreign-string (ptr)
  "TessBaseAPI's Get*Text family (GetUTF8Text, GetHOCRText, GetTsvText, etc.) all return a
heap-allocated char* that the caller owns and must free via TessDeleteText -- documented
Tesseract API convention, not followed by earlier versions of these bindings, which declared
these functions as returning CFFI :string (copies the bytes into a Lisp string but never
frees the original C buffer) and leaked that buffer on every single call. Copies ptr's
contents into a Lisp string and frees ptr, or returns NIL if ptr is a null pointer (Tesseract
returns null here if, e.g., recognition produced no output)."
  (unless (null-pointer-p ptr)
    (prog1 (foreign-string-to-lisp ptr :encoding :utf-8)
      (tess-delete-text ptr))))

(defun get-utf8-text (api)
  "This function calls TessBaseAPIGetUTF8Text on api, which should be an initialized
TessBaseAPI with its image set. If called before another function such as PROCESS-PAGES has
carried out OCR on the image, it will be carried out. On SBCL, the division-by-zero float
trap is masked to prevent it from causing a non-recoverable error.

Returns a lisp string of the UTF-8 text produced by Tesseract."
  (mask-sigfpe (owned-foreign-string (tess-base-api-get-utf8-text api))))

(defun get-hocr-text (api page)
  "This function calls TessBaseAPIGetHOCRText on api, which should be an initialized
TessBaseAPI with its image set. If called before another function such as PROCESS-PAGES has
carried out OCR on the image, it will be carried out. On SBCL, the division-by-zero float
trap is masked to prevent it from causing a non-recoverable error.

Returns a lisp string of the HOCR XML produced by Tesseract. This can be parsed using
Common Lisp XML packages such as CLOSURE-XML and plump."
  (mask-sigfpe (owned-foreign-string (tess-base-api-get-hocr-text api page))))

(defun get-tsv-text (api page)
  "Like GET-HOCR-TEXT, but calls TessBaseAPIGetTsvText, returning tab-separated-value text:
one recognized element (block/paragraph/line/word) per row, with its level, bounding box,
and confidence as columns. More compact than HOCR for programmatic consumption."
  (mask-sigfpe (owned-foreign-string (tess-base-api-get-tsv-text api page))))

(defun get-alto-text (api page)
  "Like GET-HOCR-TEXT, but calls TessBaseAPIGetAltoText, returning ALTO XML -- a layout-
analysis XML format used by libraries and archives, distinct from HOCR."
  (mask-sigfpe (owned-foreign-string (tess-base-api-get-alto-text api page))))

(defun get-page-text (api page)
  "Like GET-HOCR-TEXT, but calls TessBaseAPIGetPAGEText, returning PAGE XML (PRImA Page
Analysis and Ground-truth Elements), another layout-analysis XML format distinct from HOCR
and ALTO."
  (mask-sigfpe (owned-foreign-string (tess-base-api-get-page-text api page))))

(defun run-ocr (filepath lang psm extractor)
  "Shared by the IMAGE-TO-* functions below: initializes a TessBaseAPI for lang, sets its
page segmentation mode to psm, runs OCR on the file at filepath, then calls extractor (a
function of one argument, the recognized TessBaseAPI handle) to pull out and return the
desired output format.

psm must default to :PSM-AUTO at every call site above this function, not to whatever
TessBaseAPIInit3 itself defaults to (:PSM-SINGLE-BLOCK, confirmed by calling
TessBaseAPIGetPageSegMode immediately after init with no other calls in between) -- the
tesseract CLI tool sets :PSM-AUTO explicitly before OCR unless its own --psm flag overrides
it, so leaving TessBaseAPIInit3's raw default in place silently produces geometrically wrong
block/paragraph/line boxes on any multi-block page, not an error: confirmed directly against
a real book's title page, whose CLI-tool TSV output correctly separates title/author blocks
while the un-set-PSM API output merges the entire page into one oversized block."
  (with-base-api api
    (init-tess-api api lang)
    (tess-base-api-set-page-seg-mode api psm)
    (process-pages api (namestring (truename filepath))) ; protected from SIGFPE on sbcl
    (funcall extractor api))) ; no need to mask float traps after process-pages

(defun image-to-text (filepath &key (lang "eng") (psm :psm-auto))
  "Runs OCR on the file found at filepath for language lang (English by default), with page
segmentation mode psm (:PSM-AUTO by default, matching the tesseract CLI tool's own default --
see RUN-OCR). Returns text string."
  (run-ocr filepath lang psm #'get-utf8-text))

(defun image-to-hocr (filepath &key (lang "eng") (page 0) (psm :psm-auto))
  "Runs OCR on the file found at filepath for language lang (English by default), with page
segmentation mode psm (:PSM-AUTO by default, matching the tesseract CLI tool's own default --
see RUN-OCR). Returns HOCR xml string."
  (run-ocr filepath lang psm (lambda (api) (get-hocr-text api page))))

(defun image-to-tsv (filepath &key (lang "eng") (page 0) (psm :psm-auto))
  "Runs OCR on the file found at filepath for language lang (English by default), with page
segmentation mode psm (:PSM-AUTO by default, matching the tesseract CLI tool's own default --
see RUN-OCR). Returns tab-separated-value text describing recognized text and layout; see
GET-TSV-TEXT."
  (run-ocr filepath lang psm (lambda (api) (get-tsv-text api page))))

(defun image-to-alto (filepath &key (lang "eng") (page 0) (psm :psm-auto))
  "Runs OCR on the file found at filepath for language lang (English by default), with page
segmentation mode psm (:PSM-AUTO by default, matching the tesseract CLI tool's own default --
see RUN-OCR). Returns ALTO xml string; see GET-ALTO-TEXT."
  (run-ocr filepath lang psm (lambda (api) (get-alto-text api page))))

(defun image-to-page (filepath &key (lang "eng") (page 0) (psm :psm-auto))
  "Runs OCR on the file found at filepath for language lang (English by default), with page
segmentation mode psm (:PSM-AUTO by default, matching the tesseract CLI tool's own default --
see RUN-OCR). Returns PAGE xml string; see GET-PAGE-TEXT."
  (run-ocr filepath lang psm (lambda (api) (get-page-text api page))))
